name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build Angular
        working-directory: frontend
        run: npm run build -- --base-href "/Teste-Tecnico/"

      - name: Prepare SPA routing and disable Jekyll
        run: |
          cp frontend/dist/frontend/browser/index.html frontend/dist/frontend/browser/404.html
          touch frontend/dist/frontend/browser/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist/frontend/browser
          publish_branch: gh-pages

